# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4
set $term alacritty
set $termfloat '$term --class="float_min"'
set $browser firefox-nightly

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3
exec xfce4-clipman
# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

bindsym --release Print exec xfce4-screenshooter -c -f
bindsym --release Shift+Print exec xfce4-screenshooter -r -c
bindsym --release $mod+Print exec xfce4-screenshooter

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec $term
bindsym $mod+Shift+Return exec $term --class "float_min"

# kill focused window
bindsym $mod+Shift+q kill
bindsym $mod+q kill

#bindsym $mod+p /home/flarp/Scratch/pyvenv/bin/wal 

# start dmenu (a program launcher)
#bindsym $mod+d exec --no-startup-id dmenu_run
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop
bindsym $mod+Shift+d exec "rofi -combi-modi drun,run -modi combi -show combi"

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

#bindsym $mod+p exec /home/flarp/Scratch/pywal_update.sh

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a+Left focus parent; focus left
bindsym $mod+a+Right focus parent; focus right

bindsym --release --border button2 kill

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1:firefox:1"
set $ws2 "2:discord:2"
set $ws3 "3:code:3"
set $ws4 "4:alacritty:4"
set $ws5 "5:other:5"
set $ws6 "6:other:6"
set $ws7 "7:other:7"
set $ws8 "8:other:8"
set $ws9 "9:other:9"
set $ws10 "10:other:10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

workspace_auto_back_and_forth yes

mode "common" {
    bindsym d exec --no-startup-id discord; mode "default"
    bindsym f exec --no-startup-id firefox-nightly; mode "default"
    bindsym t exec --no-startup-id firefox-trunk; mode "default"
    bindsym c exec --no-startup-id code; mode "default"
    bindsym a exec --no-startup-id ardour; mode "default"
    bindsym m exec --no-startup-id minecraft-launcher; mode "default"
    bindsym e exec --no-startup-id eclipse; mode "default"
    bindsym g exec --no-startup-id gimp; mode "default"
    bindsym s exec --no-startup-id steam; mode "default"
    bindsym i exec --no-startup-id inkscape; mode "default"
    bindsym o exec --no-startup-id obsidian; mode "default"
    bindsym z exec --no-startup-id zotero; mode "default"
    bindsym Shift+z exec --no-startup-id zathura; mode "default"
    bindsym Escape mode "default"
}

mode "openconnect" {
    bindsym c exec /home/flarp/Scratch/start_working.sh; mode "default";
    bindsym d exec /home/flarp/Scratch/stop_openconnect.sh; mode "default"
    bindsym i exec /home/flarp/Scratch/test_openconnect.sh; mode "default"
    bindsym Escape mode "default"
}

mode "firefox" {
    bindsym c exec $browser --new-tab --url "uncc.instructure.com"; mode "default"
    bindsym g exec $browser --new-tab --url "gmail.com"; mode "default"
    bindsym a exec $browser --new-tab --url "beta.music.apple.com"; mode "default"
    bindsym Escape mode "default"
}

mode "monitor" {
    bindsym a exec xrandr --output HDMI-A-0 --auto --right-of eDP; mode "default"
    bindsym Left move workspace to output left; mode "default"
    bindsym Right move workspace to output right; mode "default"
    bindsym Escape mode "default"
}

mode "config" {
    bindsym n exec $term --class="float_min" -e nvim ~/.config/nvim/init.lua; mode "default"
    bindsym i exec $term --class="float_min" -e nvim ~/.config/i3/config ; mode "default"
    bindsym p exec $term --class="float_min" -e nvim ~/.config/polybar/config.ini ; mode "default"
    bindsym f exec $term --class="float_min" -e nvim ~/.config/fish/config.fish ; mode "default" 
    bindsym Escape mode "default"
}

mode "polybar" {
    bindsym s exec polybar-msg cmd show; mode "default"
    bindsym h exec polybar-msg cmd hide; mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+Shift+t exec date | rofi -dmenu -no-fixed-num-lines

bindsym $mod+x mode "firefox"    

bindsym $mod+o mode "openconnect"

bindsym $mod+d mode "common"

bindsym $mod+c mode "config"

bindsym $mod+Tab mode "monitor"

bindsym $mod+p mode "polybar"

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

bindsym $mod+Shift+s exec "i3-nagbar -m 'Shutdown?' -B 'Yes, shutdown' 'shutdown -P 0'"

#bindsym $mod+Shift+t exec "i3-nagbar -m 'Restart?' -B 'Yes, restart' 'shutdown -r 0'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

bindsym $mod+u exec xterm -class float -e "btm -g --mem_as_value"

bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl set 5%+
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 5%-
#bindsym F2 exec --no-startup-id brightnessctl set 5%-
#bindsym F3 exec --no-startup-id brightnessctl set 5%+

exec_always --no-startup-id ~/Scratch/start_polybar.sh

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
#bar {
#        font pango:Hack Nerd Font 9
#        status_command polybar --config=~/.config/polybar/config.ini
#        output edP
#        tray_output none
#        strip_workspace_numbers yes
#}
#
#bar {
#        font pango:Hack Nerd Font 9
#        #status_command i3status
#        output HDMI-A-0
#        tray_output none
#        strip_workspace_numbers yes
#        position top
#}

for_window [class="^.*"] border pixel 0
for_window [class="float"] floating enable, resize set 1000 500, move position center
for_window [class="float_min"] title_window_icon off, border pixel 1, floating enable, resize set 1000 500, move position center
for_window [class="float_min" tiling] border none
for_window [class="code"] move to workspace $ws3
#for_window [class="workspace-4"] move to workspace $ws4
for_window [class="firefox"] move to workspace $ws1
for_window [class="discord"] move to workspace $ws2
for_window [class="ardour-*~ds0"] floating enable
for_window [class="Zotero"] floating enable
#for_window [floating] border normal 5; title_window_icon on;

client.focused #ff4900 #ff4900 #ffffff #000000 #ff4900

exec setxkbmap -layout us,es
exec setxkbmap -option 'grp:alt_shift_toggle'
